### ISSUE TITLE
Login: Add OIDC Implementation

### ISSUE THREAD

**Issue by hifabienne** [zitadel/typescript#30]
As a developer I am able to create an OIDC / SAML session, so I can build my own login on top of ZITADEL.

**Acceptance Criteria**
- [x] Handle authorize endpoint
- [x] Proxy all OIDC requests
       - [x] Authorization Endpoint
       - [x] Token Endpoint
       - [x] well known
       - [x] userinfo
       - [x] introspection
       - [x] revoke
       - [x] end session
       - [x] device authorization
       - [x] keys
       - [x] jwt profile
- [x] Get Callback from ZITADEL API and redirect user
- [x] UI: Manage OIDC State (Get it from authorize, store it to session)
- [x] UI: Manage Authentication flow

![Image](https://github.com/zitadel/zitadel/assets/38692350/575e6a3c-e222-4ea9-8d79-b282e8cdf730)

https://jamboard.google.com/d/1UR4VPURmLJbHwdsd0W1Zw1eYp1w7UP56JiDvIsOMbos/viewer?f=1

**Comment by c0depwn** [comment]
Hi there,

I am currently trying to implement a custom self-service UI on top of my Zitadel instance. Essentially, I need this because: 

1) I don't want to directly expose Zitadel to the internet/my customers
2) Zitadel does currently not meet our customisation requirements
3) I would like to have some additional code to extend the self-service experience (by connecting with other APIs) to provide a more unified experience across similar client applications and avoid duplicating the similar implementations.

As far as I understand this is all possible since Zitadel can be used fully API driven (which is awesome :D).
Unfortunately, I'm running into the issue that my client application (I'm using zitadel-react for testing purposes) fetches the openid configuration (using the `.well-known/openid-configuration` endpoint) which causes the client app to directly use the `/authorize` from the zitadel instance because as @peintnermax mentioned, the base URL is set to the Zitadel instance.

I have attempted to modify the Zitadel confiugration (`ZITADEL_EXTERNALDOMAIN` and `ZITADEL_EXTERNALPORT`) but the base URL does not seem to change in the response. Additionally I have checked the OIDC section of the Zitadel configuration which does not seem to provide any way to modify the base URL of the openid configuration. I have also had no luck using the Zitadel console.

Is there a way to modify the base URL of the openid-configuration response via Zitadel? I'm not really happy with the client application having to modify the response from the openid confiugration endpoint as I do not want any client to see where my Zitadel instance is. Especially, since I'm not exposing it publicly.

I would appreciate some feedback or recommendations on this.

**Comment by hifabienne** [comment]
> Hi there,
> 
> I am currently trying to implement a custom self-service UI on top of my Zitadel instance. Essentially, I need this because:
> 
> 1. I don't want to directly expose Zitadel to the internet/my customers
> 2. Zitadel does currently not meet our customisation requirements
> 3. I would like to have some additional code to extend the self-service experience (by connecting with other APIs) to provide a more unified experience across similar client applications and avoid duplicating the similar implementations.
> 
> As far as I understand this is all possible since Zitadel can be used fully API driven (which is awesome :D). Unfortunately, I'm running into the issue that my client application (I'm using zitadel-react for testing purposes) fetches the openid configuration (using the `.well-known/openid-configuration` endpoint) which causes the client app to directly use the `/authorize` from the zitadel instance because as [@peintnermax](https://github.com/peintnermax) mentioned, the base URL is set to the Zitadel instance.
> 
> I have attempted to modify the Zitadel confiugration (`ZITADEL_EXTERNALDOMAIN` and `ZITADEL_EXTERNALPORT`) but the base URL does not seem to change in the response. Additionally I have checked the OIDC section of the Zitadel configuration which does not seem to provide any way to modify the base URL of the openid configuration. I have also had no luck using the Zitadel console.
> 
> Is there a way to modify the base URL of the openid-configuration response via Zitadel? I'm not really happy with the client application having to modify the response from the openid confiugration endpoint as I do not want any client to see where my Zitadel instance is. Especially, since I'm not exposing it publicly.
> 
> I would appreciate some feedback or recommendations on this.

Hi @c0depwn 
The login implemented in this repository is our login version 2 which is currently in beta.
You can find the details (current state), and how to use it in this docs page: https://zitadel.com/docs/guides/integrate/login/hosted-login#hosted-login-version-2-beta

**Comment by c0depwn** [comment]
Hi @hifabienne 

Thanks for the quick reply! I'm using both zitadel-react (to act as the OIDC client app) and this repository (to act as my custom UI). I was able to get everything working now. The issue was that I was missing the headers which need to be added when proxying OIDC requests, as mentioned in https://zitadel.com/docs/guides/integrate/login-ui/typescript-repo#oidc-proxy.
